### ISSUE TITLE
Update docs to clarify the versions supported, and mark calls that are only for "new" InfluxDb API versions

### ISSUE THREAD

**Issue by DJFliX** [pootzko/InfluxData.Net#10]
We can explain that there are basically two "versions" that this library supports: 0.9 and 1.0 (which is unreleased and basically means: everything that is not present in 0.9). Maybe we can even consolidate KAPACITOR_VERSION and INFLUX_VERSION enums as the later versions of the TICK-stack require all components to be of the same version?

**Comment by pootzko** [comment]
Yes, that's a good idea. Anyway, just installed the latest influx in a VM, ran the tests and 15 failed :D

**Comment by DJFliX** [comment]
Oh, that's a shame. Were the failing tests kapacitor related?

**Comment by pootzko** [comment]
Most of them yes, but I guess it should all be fairly easy to fix. Working on it!

**Comment by pootzko** [comment]
Updated everything, all tests pass finally, deployed to nuget.org, and updated some things in the README. Didn't add documentation for the latest stuff you added most recently yet. If you want, you could add it, or I'll do it in the next few days.
