### ISSUE TITLE
System.Net.WebException:Name Resolution

### ISSUE THREAD

**Issue by Shashidhar014** [pootzko/InfluxData.Net#11]
Getting System.Net.WebException:Name Resolution in latest xamarin.Studio 6.0.

How to resolve it?

**Comment by tihomir-kit** [comment]
Hi,

well I'm really not sure. You need to provide more information on this, a piece of code, your configuration or something... Here are a few stackoverflow threads that popped up:

http://stackoverflow.com/questions/25014110/system-net-webexception-the-remote-name-could-not-be-resolved
http://stackoverflow.com/questions/687857/sporadic-name-resolution-failure-happening-on-web-service-call

My initial assumption would be that there is an issue on your network and that your influx server name is not resolving properly for some reason.

No reply so closing.
