### ISSUE TITLE
Create New RetentionPolicy

### ISSUE THREAD

**Issue by wizdear** [pootzko/InfluxData.Net#12]
Thank you for your awesome library.
I try to use your influxData.Net in my project.
But I have some questions for using your library.

1.How to create retention policy not alter retention policy? 
2.When creating continous query, how to create query like "CREATE CONTINUOUS QUERY cq_1 ON power_data BEGIN SELECT mean(value) AS "mean_value" INTO power_data.two_hours.TEMPERATURE FROM TEMPERATURE GROUP BY host,load,time(1m) END"? As it were, how to add "GROUP BY field ...." in continous query?

I hope your advice.

**Comment by pootzko** [comment]
1. Currently that's not supported through the library in a sense of a dedicated library API method. It will be in a few days though. [DJFliX](https://github.com/DJFliX) implemented it a few weeks back but it hasn't been deployed to nuget.org yet.  

But - if you're in a hurry, you can run any arbitrary InfluxDB code using [QueryAsync](https://github.com/pootzko/InfluxData.Net#queryasync). Just write the proper InfluxDB syntax and it will do what you want.

2. [Here](https://github.com/pootzko/InfluxData.Net#createcontinuousqueryasync) is the part of documentation how to do that. If it's causing issues for you, please provide the code that you already have and then I'll help you debug it.

**Comment by pootzko** [comment]
Hi, 

a new version has just been deployed. It now supports 1) which you needed so you can check that out. If you that's it, I'll close this issue in the next few days.
