### ISSUE TITLE
Support Kapacitor tick script creation with template

### ISSUE THREAD

**Issue by ormocha** [pootzko/InfluxData.Net#18]
Hi,
In the latest Kapacitor version, there is a new feature for creating tick script templates - https://docs.influxdata.com/kapacitor/v1.0/examples/template_tasks/.
Can you add support for defining tasks using a given template?
I'll be happy to submit a PR that implements this.

**Comment by pootzko** [comment]
Hey,

that sounds great. If you have the time and will, sure, go ahead! I would be glad to accept a PR. :) If you need any help, let me know. 

Also if it's not a problem, please do it on a new branch created from dev or on dev itself.

**Comment by pootzko** [comment]
Implemented.
