### ISSUE TITLE
Kapacitor - Create enabled tasks

### ISSUE THREAD

**Issue by ormocha** [pootzko/InfluxData.Net#22]
Hi,
There is an option in kapacitor API to create a enabled task, in order to not have to do 2 request each time you create a task.
I was wondering if you can implement it. I'll be happy to submit a PR :)

**Comment by pootzko** [comment]
Hey man. Sure, if you have the time, I'll be happy to accept a PR.

This dates a while back when this separate API call didn't exist and making 2 requests was the only way to go around that.

**Comment by pootzko** [comment]
I guess not enough interest in this atm. Will close for now. If anyone is interested in it in the future, we can re-open the case.
