### ISSUE TITLE
InfluxData API responded with status code=InternalServerError, response=json: cannot unmarshal number into Go value of type struct { Points ...

### ISSUE THREAD

**Issue by adisD** [pootzko/InfluxData.Net#24]
The error message below is what the influx server returns back to the .net Client: InfluxData API responded with status code=InternalServerError, response={\"error\":\"json: cannot unmarshal number into Go value of type struct { Points ...

The server version 0.9 is running on windows

```
        IDictionary<string, object> fields = new Dictionary<string, object> { { "Severity", 0 } };
        IDictionary<string, object> tags = new Dictionary<string, object> { { "HK", "HK20" }, { "SRO", "SRO2" } };

       InfluxData.Net.InfluxDb.Models.Point point =
                            new InfluxData.Net.InfluxDb.Models.Point()
                            { 
                                Name = pointName, // "alarm-connected-to-bit",
                                Tags = tags,
                                Fields = fields,
                                Timestamp = timestamp
                            };

        return await client.Client.WriteAsync(databaseName, point);
```

**Comment by pootzko** [comment]
Hi, sorry I know this has been reported a long time ago, but I'm now going through it. Not sure if you managed to figure out what the error was here?

I tried to reproduce a WriteAsync with params you provided, but it didn't return any errors to me. I'll close this for now and if you're still interested in me looking into it, please provide a bit more details, I'll be glad to try to look into it.
