### ISSUE TITLE
Setting precision=TimeUnit.Seconds in WriteAsync() results in Error

### ISSUE THREAD

**Issue by sunserg** [pootzko/InfluxData.Net#25]
To reproduce:
Use the WriteAsync example from README.MD, change the line with WriteAsync call to:

var response = await influxDbClient.Client.WriteAsync("yourDbName", pointToWrite**, null, TimeUnit.Seconds**);

Error:
InfluxData API responded with status code=BadRequest, response={"error":"unable
to parse 'tests,SensorId=8,SerialNumber=00AF123B SensorState=\"act\",Humidity=43
1i,Temperature=22.1,Resistance=34957i 1473837346998': time outside range -922337
2036854775806 - 9223372036854775806"
}

**Comment by pootzko** [comment]
Hi,

would you be able to provide a sample object that you were trying to write to the influxdb?

**Comment by sunserg** [comment]
Hi,

This is the code that generates the error:

`  internal class Program
    {
        private static readonly InfluxDbClient influxDbClient = new InfluxDbClient("http://osboxes.XXX.global:8086/", "username", "password", InfluxDbVersion.v_1_0_0);

        private static void Main(string[] args)
        {
            RunAsync().Wait();
            Console.ReadLine();
        }

        private static async Task RunAsync()
        {
            var pointToWrite1 = new Point
            {
                Name = "tests", // serie/measurement/table to write into
                Tags = new Dictionary<string, object>
    {
        { "SensorId", 8 },
        { "SerialNumber", "00AF123B" }
    },
                Fields = new Dictionary<string, object>
    {
        { "SensorState", "act" },
        { "Humidity", 431 },
        { "Temperature", 22.1 },
        { "Resistance", 34957 }
    },
                Timestamp = DateTime.UtcNow // optional (can be set to any DateTime moment)
            };
            var pointToWrite2 = new Point
            {
                Name = "tests", // serie/measurement/table to write into
                Tags = new Dictionary<string, object>
    {
        { "SensorId", 8 },
        { "SerialNumber", "00BF123B" }
    },
                Fields = new Dictionary<string, object>
    {
        { "SensorState", "act" },
        { "Humidity", 431 },
        { "Temperature", 22.1 },
        { "Resistance", 34957 }
    },
                Timestamp = DateTime.UtcNow // optional (can be set to any DateTime moment)
            };

            var pointsToWrite = new List<Point>{ pointToWrite1, pointToWrite2 };

            try
            {
                var writeToInflux = influxDbClient.Client.WriteAsync("telegraf", pointsToWrite, null, TimeUnit.Seconds);

                Console.WriteLine("Started " + DateTime.UtcNow.ToString("hh:mm:ss.fff") + "\nPoints: " + pointsToWrite.Count);

                var response = await writeToInflux;

                Console.WriteLine("\nFinished " + DateTime.UtcNow.ToString("hh:mm:ss.fff") + "\nStatusCode: " +response.StatusCode + "\nSuccess=" + response.Success + "\nBody: " + response.Body + "\n");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
`

**Comment by pootzko** [comment]
Thnx, I'll try to look into this a bit over the weekend.

**Comment by pootzko** [comment]
I got this fixed, it will be deployed with the next nuget in a couple of days. Thanks for the report. Cheers!
