### ISSUE TITLE
InfluxDbClient.Diagnostics.GetDiagnosticsAsync() throws exception when parsing response

### ISSUE THREAD

**Issue by meverett** [pootzko/InfluxData.Net#28]
InfluxData.Net 5.0.7
.NET Framework 4.5.2
InfluxDB Server 1.0.2
Windows 7

InfluxDbClient.Diagnostics.GetDiagnosticsAsync() seems to be broken. I get a casting exception when calling the method. It looks like it is failing in DiagnosticsParser.GetDiagnosticsSystem() here:

```
var diagnosticsSystem = new DiagnosticsSystem()
{
    PID = serie.FirstRecordValueAs<long>("PID"),
    CurrentTime = DateTime.Parse(serie.FirstRecordValueAs<string>("currentTime")),
    Started = DateTime.Parse(serie.FirstRecordValueAs<string>("started")),
    Uptime = serie.FirstRecordValueAs<string>("uptime")
};
```
One of the time properties is failing to cast. By the way any reason to have Uptime be a string, versus say a TimeSpan?

Here's the exception and stack trace:

`Unable to cast object of type 'System.DateTime' to type 'System.String'.`

``at InfluxData.Net.InfluxDb.Helpers.SerieExtensions.FirstRecordValueAs[T](Serie serie, String columnKey) in D:\projects\InfluxData.Net\InfluxData.Net.InfluxDb\Helpers\SerieExtensions.cs:line 23 at InfluxData.Net.InfluxDb.ResponseParsers.DiagnosticsParser.GetDiagnosticsSystem(IEnumerable`1 series) in D:\projects\InfluxData.Net\InfluxData.Net.InfluxDb\ResponseParsers\DiagnosticsParser.cs:line 49 at InfluxData.Net.InfluxDb.ResponseParsers.DiagnosticsParser.GetDiagnostics(IEnumerable`1 series) in D:\projects\InfluxData.Net\InfluxData.Net.InfluxDb\ResponseParsers\DiagnosticsParser.cs:line 35 at InfluxData.Net.InfluxDb.ClientModules.DiagnosticsClientModule.d__5.MoveNext() in D:\projects\InfluxData.Net\InfluxData.Net.InfluxDb\ClientModules\DiagnosticsClientModule.cs:line 54``

If I get around to this I'll submit a pull request.

**Comment by pootzko** [comment]
Hi,

Thanks for the issue submission.

I believe this is connected to [this](https://github.com/pootzko/InfluxData.Net/commit/40b599a5a78147ef4c359a5f8e45e42396c69ee3). Which is pretty weird. @DJFliX made a change which then broke my unit tests (for 0.9.x and 1.0 beta I think) so I reverted it later on. I didn't put more time into debugging that, but we might have to go with his solution because v 1.0.x is more important than 0.9.x. But perhaps there is a way to make it both work. 

And I really can't remember why uptime was a string. Perhaps the response was different in 0.9.x when I implemented this and TimeSpan didn't work out. If you have the time, submit a PR, and I'll install the latest influx on my machine and run the tests against all the versions and come back to you?

**Comment by meverett** [comment]
OK, I've forked, created a feature branch off of develop, and will attempt to wrangle this. I have a fix that I've applied that seems to be working (at least with 1.0.2). I don't have 0.9 to test with. But it seems like the difference is that somehow when these values are returned from the raw query in one version they are/were returned as strings (and hence the DateTime.Parse() works) but in later versions they are somehow parsed/returned as native DateTime instances so trying to cast them as String fails.

Here's my fix which tries to take this assumption into account:

```
var diagnosticsSystem = new DiagnosticsSystem()
{
    PID = serie.FirstRecordValueAs<long>("PID"),
    CurrentTime = DateTime.Parse(serie.FirstRecordValueAs<object>("currentTime").ToString()),
    Started = DateTime.Parse(serie.FirstRecordValueAs<object>("started").ToString()),
    Uptime = serie.FirstRecordValueAs<string>("uptime")
};
```
By casting as an object we can ToString(). If the value is a string it will parse as-is in DateTime.Parse() call. If it is already a DateTime, it will convert itself to a string, which will then be Reparsed. It's a little funny going from DateTime -> String -> DateTime, but it does work.

Alternatively there would have to be some conditionals that test the value's type and then branch based on what is detected. I preferred the approach that kept the code changes minimal and less complex at the cost of a double parse.

As far as the uptime string it is a [Go duration string](https://golang.org/pkg/time/#Duration) which might look something like: `38m18.150285438s`. I'm happy to write a parser for this format. Personally I'd rather have Uptime be a TimeSpan in C# as it's inherently more useful/native. Although changing it from String would obviously break backwards compatibility. What are your thoughts? I'd also be happy to add another property, say, UptimeTimeSpan or something like that in addition to the Uptime string as-is to keep backwards compatibility and also offer a property that's much more useful.

**Comment by meverett** [comment]
Pull request submitted. I also added the UptimeTimeSpan property/parser. If you're not into the UptimeTimeSpan property, feel free to rename it or remove it. Test with 0.9 and let me know how it goes.

**Comment by pootzko** [comment]
Nice one, thanks a lot. Seems like a job well done so far.

I'll try to merge it in by the end of the weekend and publish it in v5.0.8.

I think I might even change the string for the TimeSpan. It doesn't really make sense to have both (to me at least), and it is a minor change which devs would have to fix.

Thanks again for your contribution and I'll let you know once I publish this.

**Comment by meverett** [comment]
Awesome. Glad to help. Since you were OK with the breaking change around Uptime becoming a TimeSpan I went ahead and made that change on my PR branch (and removed the UptimeTimeSpan property). I also uncommented some code in the Go duration parser I wrote so that millisecond precision is supported (before it was just up to the second).

**Comment by pootzko** [comment]
I merged this in and added a unit test for this. Not deployed yet though. I'll deploy it with everything else you made as well.
