### ISSUE TITLE
UserResponseParser.GetUsers() throws an exception when no users have been defined on the server

### ISSUE THREAD

**Issue by meverett** [pootzko/InfluxData.Net#34]
If you call `GetUsersAsync()` on the `UserClientModule` when no users have been defined on the InfluxDB server the `UserResponseParser.GetUsers()` method will throw an unhandled exception.

The code tries to send back an empty list when there are no results by copying the same technique from other response parsers but in this case the InfluxDB server returns a series with no values which doesn't get caught by the current conditional logic.

The fix is pretty simple and I've submitted pull request #33 to address it.

**Comment by pootzko** [comment]
Hey man, thanks for this. I'll merge it in and deploy this weekend.

**Comment by pootzko** [comment]
Sorry, was a bit occupied. I think I'll deploy this in the next two days. Cheers.

**Comment by pootzko** [comment]
Will deploy this in a new nuget version tomorrow (today :D). Cheers!

**Comment by pootzko** [comment]
Deployed with v6,0,1. Thanks again.
