### ISSUE TITLE
Ability to handle chunked query responses ?

### ISSUE THREAD

**Issue by gsokoll** [pootzko/InfluxData.Net#36]
Is there a means to support chunked query responses, eg if I run a query that returns a large number of results, the values are limited to 10,000.  
see https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/#chunking

If I run this query on my db, it should return approx 500,000 results but only returns the first 10,000
`select * from history where time > '2017-01-10' and time < '2017-02-10'`

I tried adding the "chunked=true" option to the query string, but that results in an exception:
_"InfluxData API responded with status code=BadRequest, response={"error":"error parsing query: found chunked, expected ; at line 1, char 91"}"_

**Comment by pootzko** [comment]
Hi @gsokoll 

unfortunately there is no support for chunked queries at the moment, but I see that there is a [fork](https://github.com/apppies/InfluxData.Net/commit/76019ded44ca4b1987c1ae2be866d2a82a5efcf0) where it is being worked on. So perhaps in a few days it might be there.

**Comment by gsokoll** [comment]
Thanks Pootzko.  I had started looking through the code myself and was about to try implementing chunked support as a fork - didn't realise there was already a fork working on it.

**Comment by pootzko** [comment]
I can't vouch that that person ([@appies](https://github.com/apppies)) will finish it (maybe it is already finished, I'm not sure) and make a PR. Hopefully he does. I simply saw that he made a fork yesterday and added a bit of code to it. If you feel like helping out, I suppose you could ask him if he needs any assistance.

**Comment by gsokoll** [comment]
Yes, I will have a closer look at it and see if I can help in any way.

**Comment by pootzko** [comment]
Resolved by #39, Just needs to be deployed to nuget.org.
