### ISSUE TITLE
Allow specifying the timestamp precision when querying data

### ISSUE THREAD

**Issue by semigroupoid** [pootzko/InfluxData.Net#38]
According to the Influxdb documentation (https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/), it is possible to specify the timestamp format for query results by using the 'epoch' query string parameter in the corresponding HTTP request.
I believe this could be implemented in InfluxData.Net by adding an additional optional parameter for the epoch precision ([h,m,s,ms,u,ns]) to the query methods (or by adding further overloaded methods).
I'm willing to implement this if you are open to a pull request.

**Comment by pootzko** [comment]
Hi semigroupoid

Sure! I'll be happy to accept a PR. Thnx :)
