### ISSUE TITLE
query with & or # cannot be encoded correctly in url and failed in query API

### ISSUE THREAD

**Issue by micastle** [pootzko/InfluxData.Net#44]
my query is like this:
select * from int_metrics where "host"='my O&O' limit 5

it works with influx.exe, but when call with the client, it reports failure due to url encoding is using Uri.EscapeUriString, which does not encode the character &. it happens in InfluxData.Net\InfluxData.Net.Common\Helpers\HttpUtility.cs, I suggest to use Uri.EscapeDataString to avoid this.

**Comment by pootzko** [comment]
Thnx for the suggestion. Will test it and fix it up for the next version. It might also help with an issue with submitting regexes to influx api as well.

**Comment by pootzko** [comment]
Just [for the reference](https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring).

**Comment by pootzko** [comment]
Alright, all test are still passing and it makes sense to use the EscapeDataString instead. Thanks for the suggestion and sorry for the wait. I'll deploy this tonight.
