### ISSUE TITLE
CreateBatchWriter method mistakenly awaited in the docs

### ISSUE THREAD

**Issue by Zero3** [pootzko/InfluxData.Net#46]
According to the docs, one is supposed to create a `BatchWriter` like this:

````
var batchWriter = await influxDbClient.Serie.CreateBatchWriter("yourDbName");
````

However, the `CreateBatchWriter` method is not awaitable, and the `await` is thus invalid.

**Comment by pootzko** [comment]
Thnx. Will fix.

**Comment by pootzko** [comment]
Fixed.
