### ISSUE TITLE
Missing UrlEncoding of database name and query

### ISSUE THREAD

**Issue by hpbieker** [pootzko/InfluxData.Net#48]
I have a Influx database called 'XXX+' and some measurements called 'XXX+YYY'. InfluxData.Net failes to read this data because the database name and the query is not URL encoded. This means that the "+" is passed directly to influxdb, which URL decodes the "+" to space.

Would it be possible to fix this?

**Comment by hpbieker** [comment]
This change to HttpUtility fixes the problem (the second fix is not required, but should be added anyway):
        public static string UrlEncode(string value)
        {
            return Uri.EscapeUriString(value)
                **.Replace("+", "%2B")**
                .Replace(";", "%3B")
                .Replace("[", "%5B")
                .Replace("]", "%5D")
                **.Replace("{", "%7B")**
                .Replace("}", "%7D");
        }

**Comment by pootzko** [comment]
Hi, thanks for this. I believe this is probably also connected to #43 and #44 and #45. This fix seems quite simple, so I might publish this as a change over the weekend if I find time.

And also, I just can't not tell it :D I think it's not good to use characters such as + in table names because it calls for trouble, but that's my 2c only.

**Comment by hpbieker** [comment]
Perfect. Will you post a new release on nuget as well?

I know + is not the best character to have in names, but on the other hand we get to check that we do the correct uriencodings and uridecodings in our infrastructure :-)

**Comment by pootzko** [comment]
Yes, that's what I meant. Publish as a new version of the nuget. Cheers!

**Comment by hpbieker** [comment]
Perfect!

**Comment by hpbieker** [comment]
Did you get the time to fix it? Need it for the software we make :-)

**Comment by pootzko** [comment]
Hey! Sorry for the delay. 

Based on the feedback from #44, I actually completely removed the `HttpUtility.UrlEncode()` and replaced it with `Uri.EscapeDataString()`. I believe this should sort your issue as well. I deployed this with v7.0.1. 

Could you please let me know if that helped when you get the chance?

Thanks!

**Comment by hpbieker** [comment]
It worked fine! Thanks.
