### ISSUE TITLE
Inserting string values like "with space" result in "with\ space"

### ISSUE THREAD

**Issue by djpable** [pootzko/InfluxData.Net#49]
I'm not able to implement the following insert:
`INSERT cpu,host=serverA,region=us_west value="with space"`
or via REST:
`curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server02 value="with space"`

Could you verify and post a piece of code to not escape spaces with "\ "?

**Comment by hpbieker** [comment]
Looks like an issue with influx and not this library?

**Comment by djpable** [comment]
The problem is in the class PointFormatter, in this piece of code:

```
        protected virtual string EscapeNonTagValue(string value)
        {
            Validate.IsNotNull(value, "value");
            var result = value
                // literal backslash escaping is broken
                // https://github.com/influxdb/influxdb/issues/3070
                .Replace(@"\", @"\\")
                .Replace(@"""", @"\""") // TODO: check if this is right or if "" should become \"\"
                .Replace(@" ", @"\ ")
                .Replace(@"=", @"\=")
                .Replace(@",", @"\,");

            return result;
        }
```

There is an explicit introduction of a backslache before every space.
It's not an InfluxDB issue. Inserting strings containing spaces from command line is working,
and https://github.com/influxdata/influxdb-csharp library for example is not bugged like this.

**Comment by pootzko** [comment]
The thing is, InfluxData.Net has been forked from [InfluxDB.Net](https://github.com/ziyasal/InfluxDb.Net/) and that piece of code was [inherited](https://github.com/ziyasal/InfluxDB.Net/blob/ca52faa3b83d6d4aa5862a1ae1fc3a565ee5ac47/InfluxDB.Net/Infrastructure/Formatters/FormatterBase.cs) from the original library. And I'm not fully sure what specific escape is there.

I tried to comment out that specific line and all the tests I have still passed, but I'm a bit afraid to remove that replace and to deploy this change to production.

**Comment by pootzko** [comment]
Actually, it seems that the documentation for older versions [did require escaping](https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/). But that then makes it a bit weird that all the tests passed..

**Comment by pootzko** [comment]
[More info](https://docs.influxdata.com/influxdb/v0.9/write_protocols/write_syntax/#escaping-characters):

> If a tag key, tag value, or field key contains a space , comma ,, or an equals sign = it must be escaped using the backslash character \. Backslash characters do not need to be escaped. Commas , and spaces will also need to be escaped for measurements, though equals signs = do not.

**Comment by pootzko** [comment]
Could you please provide me with a piece of C# code which you're using to insert this value so I could fully reproduce your issue and try to do something about it? 

Also, for the reference, this is the escaping documentation for 1.2 (I might need it to fix this):
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#special-characters
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#special-characters

I assume you're using InfluxDB v1.2?

**Comment by djpable** [comment]
I have read it well, I copy and past it here so you can read it better:

Special Characters For tag keys, tag values, and field keys always use a backslash character \ to escape:
- commas ,
- equal signs =
- spaces
For measurements always use a backslash character \ to escape:
- commas ,
- spaces
For string field values use a backslash character \ to escape:
- double quotes "
Line Protocol does not require users to escape the backslash character \. Users do not need to escape all other special characters. Examples
Example 1: Write a point with special characters
`
 > INSERT "measurement\ with\ quo⚡️es\ and\ emoji",tag\ key\ with\ sp🚀ces=tag\,value\,with"commas" **field_k\ey="string field value, only \" need be esc🍭ped"**
`

**Comment by pootzko** [comment]
Hi, thanks! 

I assume you used `BasicClientModule.QueryAsync()` with that insert that you just posted? Or did you use a different lib module?

Thnx

**Comment by luposky** [comment]
I have the same issue, writing (WriteAsync) textual event data with this lib, result in improper escaped text.

This is a screen shot of a grafana dashboard:

![image](https://user-images.githubusercontent.com/1070180/30969499-dbfb2b9e-a462-11e7-915f-dc4b0d37e17f.png)

**Comment by pootzko** [comment]
Updated the formatter to match the [docs](https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#special-characters). Not deployed to nuget yet because I have a few more things to update in the library before that. If you need this asap, feel free to use the dev branch.

**Comment by pootzko** [comment]
I'll deploy this shortly as part of nuget v8. If you find any bugs with it, please reopen the case. And thanks everyone for help!

**Comment by sanchomuzax** [comment]
It's works for me (with `"` char):

~~~
mytag="white\ spaces"
ct=123
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary "stringtest,tag=$mytag value=$ct"
~~~

The whitespaces problem solved with CURL on InfluxDB.
