### ISSUE TITLE
Add support for netstandard + dotnet-core

### ISSUE THREAD

**Issue by hanssens** [pootzko/InfluxData.Net#50]
As discussed in PR #35, we need to support dotnet-core

- [x] Convert solution to netstandard
- [x] Ensure compatibility with .NET 4.6+
- [x] Ensure compatibility with dotnet-core v1.x
- [ ] Configure NuGet details in project properties (.csproj)
- [x] publish NuGet package update

**Comment by ignatandrei** [comment]
Please do it ;-)

**Comment by hanssens** [comment]
All that remains is configuring the NuGet package properly and update it. Can you help me with this, @pootzko?

**Comment by pootzko** [comment]
Hi,

sure. I've glanced over the work and it seems pretty solid. Thanks! I'll work on deploying this over the following weekend.

**Comment by pootzko** [comment]
A quick update - I'm working on this. 

https://www.nuget.org/packages/InfluxData.Net.Test

net461 works fine, but I have to figure out how to make netstandard1.4 to work..

![image](https://user-images.githubusercontent.com/535842/29253950-36ee00a8-8082-11e7-9c38-dc0d8b1de374.png)

**Comment by pootzko** [comment]
Hey! I just published the Nuget and the [v7.0.2](https://www.nuget.org/packages/InfluxData.Net/7.0.2) now supports .Net Standard 2.0 (upgraded from 1.6). 

I also added a "NugetTests" subfolder which contains a solution with 2 projects (One for .Net Framework and one for .Net Core). Both of them have a copy of the integration tests and I used them to pull down the published nuget to test that everything still works fine.

If you find out something's not working properly, please let me know. 

And a massive thanks for the upgrade @hanssens :)

**Comment by hanssens** [comment]
Awesome, great work @pootzko! I'll try it soon.

**Comment by hanssens** [comment]
It blends like a charm! 👍🏻
