### ISSUE TITLE
Connect with SSL

### ISSUE THREAD

**Issue by Henna1977** [pootzko/InfluxData.Net#56]
Is there a way to use https with an self signed certificate?
I didn't find a solution right now.

**Comment by Henna1977** [comment]
Solution found

**Comment by pootzko** [comment]
Hi!

would you mind sharing how you solved it? :)

Thnx!

**Comment by Henna1977** [comment]
Actually, it was not a problem of InfluxData.Net but the HttpClient.
This raises an error message when the connection is self signed.

For this error, I have redirected the event handler.

`ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`

It's just a quick solution but it works for me.
