### ISSUE TITLE
Facing error The underlying connection was closed: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by programmer-pragmatic** [pootzko/InfluxData.Net#57]
I created one account on aiven and tried to access InfluxDB using following code:

            var influxDbClient = new InfluxDbClient("http://influx-3eb0406b.myName-aae2.aivencloud.com:15892/", "avnadmin", "PasswXXXXord", InfluxDbVersion.v_1_0_0);

            influxDbClient.Database.CreateDatabaseAsync("newDbName").Wait();

But it return error "The underlying connection was closed: The connection was closed unexpectedly"

**Comment by pootzko** [comment]
Hey,

could you please provide more details for this bug? This is not enough details for me to give you any kind of suggestion, I can't debug this.

Thanks

**Comment by pootzko** [comment]
No reply, closing.
