### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mmaddipatla** [pootzko/InfluxData.Net#6]
I am processing a csv file whose each column maps to a metric. I am sending the fields in a single row in bulk via the WriteSync method. 
One row, typically has around 500 points.

When i try to process the lines which i have read in memory in parallel, via code like following:
Parallel.ForEach(lines.Skip(1),new ParallelOptions() { MaxDegreeOfParallelism = 5 }, line =>
                  {
                      try
                      {
                                   TransformLine(line, columnHeaderInfo.ColumnHeaders);
                      }
                      catch (Exception exp)
                      {
                          exceptions.Enqueue(exp);
                      }
                  });

i start getting Internal Server Error, even with Parallelism set to only 5.  Are there any settings i need to ensure in my influxdb.conf file? Any help in resolving this will be highly appreciated.

Currently to process a 4 MB file, it takes around 11 mins.

**Comment by pootzko** [comment]
Hi,

I would need a bit more data on this.. Lines is of what type of object? What is the exact server error that you get? You need to be more specific.

**Comment by pootzko** [comment]
No reply, closing.
