### ISSUE TITLE
Has this client been tested on downlevel revisions of .NET framework?

### ISSUE THREAD

**Issue by ajcaldera1** [pootzko/InfluxData.Net#65]
Has this client been tested on .NET Framework 2.0?

**Comment by tihomir-kit** [comment]
Hi, no it hasn't. I'm targeting .Net 4.6.1 and .Net Standard 2.0. Supporting .Net 2.0 would require much more time from my end which I unfortunately can't really afford at this stage.

**Comment by awb99** [comment]
I tried to compile with. Net 4.6.1 and I am getting errors like 'conflict between different version of same dependency'.  I think somehow the system.net.http library references 4.1.1.1 but in nuget it gets now 4.1.1.2. I am trying to change the binding via the app. Config  but so far haven't been lucky...

**Comment by tihomir-kit** [comment]
@awb99 could you please open a separate issue for this? I don't think the two are related. Thnx.
