### ISSUE TITLE
Massive multi-threaded writes uses up all tcp ports

### ISSUE THREAD

**Issue by HakanL** [pootzko/InfluxData.Net#8]
I'm getting this error:
Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted

when I'm pushing the WriteAsync method hard from multiple threads. If I understand the error correctly it indicates that a new connection is created for each write. Is there a way where we can reuse an existing connection instead?

**Comment by pootzko** [comment]
Hi HakanL,

I actually had a very similar [issue](https://github.com/ziyasal/InfluxDB.Net/issues/8) while I was using [ziyasal's InfluxDB.Net](https://github.com/ziyasal/InfluxDB.Net). I tried to make a singleton wrapper around the `HttpClient` to reuse the same connection but after testing it I realized i was still getting new connections all the time.. So the library currently doesn't handle that. 

However, I managed to go around that problem by batching my writes. [Here](https://github.com/pootzko/InfluxData.Net/issues/5) is the ticket that was opened for that. In that thread I provided some sample code for how to batch the writes. Perhaps that might be a good enough solution for you for now. It significantly reduced the stress from the InfluxDB machine in our case. The only downside is - we now have a "listener app" which handles incoming readings, batches them and then submits them to the DB.

If you have some spare time (that you're reaaaalllly not sure what to do with :D ) , perhaps you could try to modify the library to make it reuse an existing connection and test that?

**Comment by HakanL** [comment]
Turns out there are 5-6 different .NET clients for Influx so I ended up using a different one that didn't have this issue.

**Comment by pootzko** [comment]
Glad you managed to make it work out for you. :)

Would you mind please telling me which client did you end up using so I could take a look how they did it? It might help me resolve the issue in this library as well. Thanks.

**Comment by HakanL** [comment]
Yea of course! https://github.com/nblumhardt/influxdb-lineprotocol

**Comment by pootzko** [comment]
Thanks!

**Comment by pootzko** [comment]
This has been fixed with the v5.0.1.
